[build-system]
requires = [
    "setuptools>=45",
    "wheel", 
    "pybind11>=2.6.0",
    "cmake>=3.12",
    "numpy>=1.19.0",
]
build-backend = "setuptools.build_meta"

[project]
name = "vsla"
version = "0.1.0"
description = "Variable-Shape Linear Algebra: Mathematical foundations and high-performance implementation"
readme = "README.md"
license = {text = "MIT"}
authors = [
    {name = "Royce Birnbaum", email = "royce.birnbaum@gmail.com"}
]
maintainers = [
    {name = "Royce Birnbaum", email = "royce.birnbaum@gmail.com"}
]
keywords = [
    "linear-algebra",
    "tensors", 
    "semiring",
    "automatic-differentiation",
    "high-performance-computing"
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: C",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9", 
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Mathematics",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
requires-python = ">=3.8"
dependencies = [
    "numpy>=1.19.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=6.0",
    "pytest-benchmark",
    "black",
    "flake8", 
    "mypy",
    "pre-commit",
]
benchmarks = [
    "scipy>=1.7.0",
    "matplotlib>=3.3.0",
]
docs = [
    "sphinx>=4.0",
    "sphinx-rtd-theme",
    "myst-parser",
]
all = [
    "vsla[dev,benchmarks,docs]"
]

[project.urls]
"Homepage" = "https://github.com/royce-birnbaum/vsla"
"Bug Tracker" = "https://github.com/royce-birnbaum/vsla/issues"
"Documentation" = "https://github.com/royce-birnbaum/vsla/blob/main/README.md"
"Source Code" = "https://github.com/royce-birnbaum/vsla"
"Changelog" = "https://github.com/royce-birnbaum/vsla/blob/main/CHANGELOG.md"

[tool.setuptools]
package-dir = {"" = "python"}

[tool.setuptools.packages.find]
where = ["python"]

# Black code formatting
[tool.black]
line-length = 88
target-version = ['py38', 'py39', 'py310', 'py311', 'py312']
include = '\.pyi?$'
extend-exclude = '''
/(
  # directories
  \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | build
  | dist
)/
'''

# Flake8 linting
[tool.flake8]
max-line-length = 88
extend-ignore = ["E203", "W503"]
exclude = [
    ".git",
    "__pycache__",
    "build",
    "dist",
    ".eggs",
    "*.egg-info",
]

# MyPy type checking
[tool.mypy]
python_version = "3.8"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_no_return = true
warn_unreachable = true
strict_equality = true

[[tool.mypy.overrides]]
module = [
    "numpy.*",
    "scipy.*",
    "matplotlib.*",
]
ignore_missing_imports = true

# Pytest configuration
[tool.pytest.ini_options]
testpaths = ["tests", "python/tests"]
python_files = ["test_*.py", "*_test.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
addopts = [
    "--strict-markers",
    "--strict-config",
    "--verbose",
]
markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
    "integration: marks tests as integration tests",
    "benchmark: marks tests as benchmarks",
]

# Coverage configuration
[tool.coverage.run]
source = ["python/vsla"]
omit = [
    "*/tests/*",
    "*/test_*",
]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "if self.debug:",
    "if settings.DEBUG",
    "raise AssertionError",
    "raise NotImplementedError",
    "if 0:",
    "if __name__ == .__main__.:",
    "class .*\\bProtocol\\):",
    "@(abc\\.)?abstractmethod",
]